sudo: required

language: python

services:
  - docker

python:
  - 3.6

before_script:
  - ls -lah
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d 
  - docker ps -a
  - sleep 30  

script: python ./tests/test.py

after_script:
  - docker-compose down



notifications:
  email:
    recipients:
      - cdd@sdu.dk
    on_success: always
